/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package logins;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Second extends javax.swing.JFrame {

    /** Creates new form Second */
    public Second() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TotalField2 = new javax.swing.JTextField();
        NumField2 = new javax.swing.JTextField();
        DateField2 = new javax.swing.JTextField();
        iTemnameField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PriceField2 = new javax.swing.JTextField();
        Bexit1 = new javax.swing.JButton();
        BBack1 = new javax.swing.JButton();
        BAdd2 = new javax.swing.JButton();
        BDelete2 = new javax.swing.JButton();
        Bupdate2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ATable2 = new javax.swing.JTable();
        Bclear2 = new javax.swing.JButton();
        BuyField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel2.setMaximumSize(new java.awt.Dimension(853, 528));
        jPanel2.setPreferredSize(new java.awt.Dimension(853, 528));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Minion Pro SmBd", 1, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Keep Records");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 4));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("No of Items");
        jLabel5.setToolTipText("");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Date");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Item Name");
        jLabel7.setToolTipText("");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total Price");
        jLabel8.setToolTipText("");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TotalField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TotalField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TotalField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalField2ActionPerformed(evt);
            }
        });

        NumField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NumField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DateField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DateField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DateField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DateField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateField221ActionPerformed(evt);
            }
        });

        iTemnameField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        iTemnameField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iTemnameField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Price Per Item");
        jLabel9.setToolTipText("");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        PriceField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PriceField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PriceField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Bexit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bexit1.setText("Exit");
        Bexit1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        Bexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bexit1ActionPerformed(evt);
            }
        });

        BBack1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BBack1.setText("Back");
        BBack1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        BBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBack1ActionPerformed(evt);
            }
        });

        BAdd2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BAdd2.setText("Add");
        BAdd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAdd21ActionPerformed(evt);
            }
        });

        BDelete2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDelete2.setText("Delete");
        BDelete2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDelete21ActionPerformed(evt);
            }
        });

        Bupdate2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bupdate2.setText("Update");
        Bupdate2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Bupdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bupdate21ActionPerformed(evt);
            }
        });

        ATable2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ATable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Item Name", "No of Items", "Price Per Item", "Total price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ATable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ATable21MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ATable2);

        Bclear2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bclear2.setText("Clear");
        Bclear2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Bclear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bclear21ActionPerformed(evt);
            }
        });

        BuyField.setEditable(false);
        BuyField.setBackground(new java.awt.Color(0, 0, 0));
        BuyField.setFont(new java.awt.Font("Minion Pro SmBd", 1, 36)); // NOI18N
        BuyField.setForeground(new java.awt.Color(255, 255, 255));
        BuyField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BuyField.setText("BUY");
        BuyField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DateField2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(iTemnameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NumField2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PriceField2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(595, 595, 595)
                                .addComponent(Bexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TotalField2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(BAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bupdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bclear2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jTextField2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(DateField2))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iTemnameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(Bclear2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bupdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotalField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalField2ActionPerformed

    private void DateField221ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateField221ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateField221ActionPerformed

    private void Bexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bexit1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Bexit1ActionPerformed

    private void BBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBack1ActionPerformed
        // TODO add your handling code here:
        dispose();

        FirstPaGe Info=new FirstPaGe ();
        Info.setVisible(true);
    }//GEN-LAST:event_BBack1ActionPerformed

    private void BAdd21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAdd21ActionPerformed
        // TODO add your handling code here

        DefaultTableModel model=(DefaultTableModel) ATable2.getModel();

        if(!DateField2.getText().trim().equals("") && !iTemnameField2.getText().trim().equals("") && !NumField2.getText().trim().equals("") && !PriceField2.getText().trim().equals("")){

            double a=Double.parseDouble(NumField2.getText());
            double b=Double.parseDouble(PriceField2.getText());
            double total=a*b;
            String z=Double.toString(total);
            TotalField2.setText(z);
            model.addRow(new Object[]{DateField2.getText(),iTemnameField2.getText(),NumField2.getText(),PriceField2.getText(),  TotalField2.getText()});
        }else {
            JOptionPane.showMessageDialog(null, "Add Data Properly","Message",1);
            // Message.setText("");
            //jLabel1.setText("Add Data Properly");
        }
        DateField2.setText(null);
        iTemnameField2.setText(null);
        PriceField2.setText(null);
        NumField2.setText(null);
        TotalField2.setText(null);
    }//GEN-LAST:event_BAdd21ActionPerformed

    private void BDelete21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDelete21ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) ATable2.getModel();
        if(ATable2.getSelectedRow()==-1){
            if(ATable2.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"Table is Empty","Message", 1);
            }else{
                JOptionPane.showMessageDialog(null,"Select an item","Message", 1);
            }
        }else{
            model.removeRow(ATable2.getSelectedRow());

        }
    }//GEN-LAST:event_BDelete21ActionPerformed

    private void Bupdate21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bupdate21ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) ATable2.getModel();
        if(ATable2.getSelectedRow()==-1){
            if(ATable2.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"Table is Empty","Message", 1);
            }else{
                JOptionPane.showMessageDialog(null,"Select an item","Message", 1);
            }
        }else{
            model.setValueAt(DateField2.getText(), ATable2.getSelectedRow(),0);
            model.setValueAt(iTemnameField2.getText(), ATable2.getSelectedRow(),1);
            model.setValueAt(NumField2.getText(), ATable2.getSelectedRow(),2);
            model.setValueAt(PriceField2.getText(), ATable2.getSelectedRow(),3);
            double a=Double.parseDouble(NumField2.getText());
            double b=Double.parseDouble(PriceField2.getText());
            double total=a*b;
            String z=Double.toString(total);
            TotalField2.setText(z);
            model.setValueAt(TotalField2.getText(), ATable2.getSelectedRow(),4);}
    }//GEN-LAST:event_Bupdate21ActionPerformed

    private void ATable21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ATable21MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) ATable2.getModel();
        DateField2.setText((String) model.getValueAt(ATable2.getSelectedRow(), 0));
        iTemnameField2.setText((String) model.getValueAt(ATable2.getSelectedRow(), 1));
        NumField2.setText((String) model.getValueAt(ATable2.getSelectedRow(), 2));
        PriceField2.setText((String) model.getValueAt(ATable2.getSelectedRow(), 3));
          double a=Double.parseDouble(NumField2.getText());
            double b=Double.parseDouble(PriceField2.getText());
            double total=a*b;
            String z=Double.toString(total);
            TotalField2.setText(z);
        TotalField2.setText((String) model.getValueAt(ATable2.getSelectedRow(), 4));
    }//GEN-LAST:event_ATable21MouseClicked

    private void Bclear21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bclear21ActionPerformed
        // TODO add your handling code here:
            DateField2.setText(null);
            iTemnameField2.setText(null);
            NumField2.setText(null);
            PriceField2.setText(null);
            TotalField2.setText(null);
            
            
    }//GEN-LAST:event_Bclear21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Second().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ATable2;
    private javax.swing.JButton BAdd2;
    private javax.swing.JButton BBack1;
    private javax.swing.JButton BDelete2;
    private javax.swing.JButton Bclear2;
    private javax.swing.JButton Bexit1;
    private javax.swing.JButton Bupdate2;
    private javax.swing.JTextField BuyField;
    private javax.swing.JTextField DateField2;
    private javax.swing.JTextField NumField2;
    private javax.swing.JTextField PriceField2;
    private javax.swing.JTextField TotalField2;
    private javax.swing.JTextField iTemnameField2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
