/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Third_PaGe extends javax.swing.JFrame {

    /**
     * Creates new form Third_PaGe
     */
    public Third_PaGe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TotalField1 = new javax.swing.JTextField();
        NumField1 = new javax.swing.JTextField();
        DateField1 = new javax.swing.JTextField();
        iTemnameField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PriceField1 = new javax.swing.JTextField();
        Bexit1 = new javax.swing.JButton();
        BBack1 = new javax.swing.JButton();
        BAdd1 = new javax.swing.JButton();
        BDelete1 = new javax.swing.JButton();
        Bupdate1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ATable1 = new javax.swing.JTable();
        Bclear1 = new javax.swing.JButton();
        SellField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel2.setMaximumSize(new java.awt.Dimension(853, 528));
        jPanel2.setPreferredSize(new java.awt.Dimension(853, 528));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Minion Pro SmBd", 1, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Keep Records");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 4));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("No of Items");
        jLabel5.setToolTipText("");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Date");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Item Name");
        jLabel7.setToolTipText("");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total Price");
        jLabel8.setToolTipText("");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TotalField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TotalField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TotalField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalField1ActionPerformed(evt);
            }
        });

        NumField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NumField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DateField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DateField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DateField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DateField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateField11ActionPerformed(evt);
            }
        });

        iTemnameField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        iTemnameField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iTemnameField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Price Per Item");
        jLabel9.setToolTipText("");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        PriceField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PriceField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PriceField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Bexit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bexit1.setText("Exit");
        Bexit1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        Bexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bexit1ActionPerformed(evt);
            }
        });

        BBack1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BBack1.setText("Back");
        BBack1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        BBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBack1ActionPerformed(evt);
            }
        });

        BAdd1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BAdd1.setText("Add");
        BAdd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAdd11ActionPerformed(evt);
            }
        });

        BDelete1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BDelete1.setText("Delete");
        BDelete1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDelete11ActionPerformed(evt);
            }
        });

        Bupdate1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bupdate1.setText("Update");
        Bupdate1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Bupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bupdate11ActionPerformed(evt);
            }
        });

        ATable1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ATable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Item Name", "No of Items", "Price Per Item", "Total price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ATable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ATable11MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ATable1);

        Bclear1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bclear1.setText("Clear");
        Bclear1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Bclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bclear11ActionPerformed(evt);
            }
        });

        SellField.setEditable(false);
        SellField.setBackground(new java.awt.Color(0, 0, 0));
        SellField.setFont(new java.awt.Font("Minion Pro SmBd", 1, 36)); // NOI18N
        SellField.setForeground(new java.awt.Color(255, 255, 255));
        SellField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SellField.setText("SELL");
        SellField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 4));
        SellField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DateField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(iTemnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NumField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PriceField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(595, 595, 595)
                                .addComponent(Bexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TotalField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(SellField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(SellField))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(DateField1))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iTemnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(Bclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotalField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalField1ActionPerformed

    private void DateField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateField11ActionPerformed

    private void Bexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bexit1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Bexit1ActionPerformed

    private void BBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBack1ActionPerformed
        // TODO add your handling code here:
        dispose();

        FirstPaGe Info=new FirstPaGe ();
        Info.setVisible(true);
    }//GEN-LAST:event_BBack1ActionPerformed

    private void BAdd11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAdd11ActionPerformed
        // TODO add your handling code here
       

        DefaultTableModel model=(DefaultTableModel) ATable1.getModel();

        if(!DateField1.getText().trim().equals("") && !iTemnameField1.getText().trim().equals("") && !NumField1.getText().trim().equals("") && !PriceField1.getText().trim().equals("")){
         
            double a=Double.parseDouble(NumField1.getText());
        double b=Double.parseDouble(PriceField1.getText());
        double total=a*b;
        String z=Double.toString(total);
        TotalField1.setText(z);
            model.addRow(new Object[]{DateField1.getText(),iTemnameField1.getText(),NumField1.getText(),PriceField1.getText(),  TotalField1.getText()});
        }else {
            JOptionPane.showMessageDialog(null, "Add Data Properly","Message",1);
            // Message.setText("");
            //jLabel1.setText("Add Data Properly");
        }
        DateField1.setText(null);
        iTemnameField1.setText(null);
        PriceField1.setText(null);
        NumField1.setText(null);
        TotalField1.setText(null);

    }//GEN-LAST:event_BAdd11ActionPerformed

    private void BDelete11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDelete11ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) ATable1.getModel();
        if(ATable1.getSelectedRow()==-1){
            if(ATable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"Table is Empty","Message", 1);
            }else{
                JOptionPane.showMessageDialog(null,"Select an item","Message", 1);
            }
        }else{
            model.removeRow(ATable1.getSelectedRow());

        }
    }//GEN-LAST:event_BDelete11ActionPerformed

    private void Bupdate11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bupdate11ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) ATable1.getModel();
        if(ATable1.getSelectedRow()==-1){
            if(ATable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"Table is Empty","Message", 1);
            }else{
                JOptionPane.showMessageDialog(null,"Select an item","Message", 1);
            }
        }else{
            model.setValueAt(DateField1.getText(), ATable1.getSelectedRow(),0);
            model.setValueAt(iTemnameField1.getText(), ATable1.getSelectedRow(),1);
            model.setValueAt(NumField1.getText(), ATable1.getSelectedRow(),2);
            model.setValueAt(PriceField1.getText(), ATable1.getSelectedRow(),3);
            double a=Double.parseDouble(NumField1.getText());
            double b=Double.parseDouble(PriceField1.getText());
            double total=a*b;
            String z=Double.toString(total);
            TotalField1.setText(z);
            model.setValueAt(TotalField1.getText(), ATable1.getSelectedRow(),4);}
    }//GEN-LAST:event_Bupdate11ActionPerformed

    private void ATable11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ATable11MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) ATable1.getModel();
        DateField1.setText((String) model.getValueAt(ATable1.getSelectedRow(), 0));
        iTemnameField1.setText((String) model.getValueAt(ATable1.getSelectedRow(), 1));
        NumField1.setText((String) model.getValueAt(ATable1.getSelectedRow(), 2));
        PriceField1.setText((String) model.getValueAt(ATable1.getSelectedRow(), 3));
          double a=Double.parseDouble(NumField1.getText());
            double b=Double.parseDouble(PriceField1.getText());
            double total=a*b;
            String z=Double.toString(total);
            TotalField1.setText(z);
        TotalField1.setText((String) model.getValueAt(ATable1.getSelectedRow(), 4));
    }//GEN-LAST:event_ATable11MouseClicked

    private void Bclear11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bclear11ActionPerformed
        // TODO add your handling code here:
        DateField1.setText(null);
        iTemnameField1.setText(null);
        NumField1.setText(null);
        PriceField1.setText(null);
        TotalField1.setText(null); 
    }//GEN-LAST:event_Bclear11ActionPerformed

    private void SellFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SellFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Third_PaGe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Third_PaGe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Third_PaGe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Third_PaGe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Third_PaGe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ATable1;
    private javax.swing.JButton BAdd1;
    private javax.swing.JButton BBack1;
    private javax.swing.JButton BDelete1;
    private javax.swing.JButton Bclear1;
    private javax.swing.JButton Bexit1;
    private javax.swing.JButton Bupdate1;
    private javax.swing.JTextField DateField1;
    private javax.swing.JTextField NumField1;
    private javax.swing.JTextField PriceField1;
    private javax.swing.JTextField SellField;
    private javax.swing.JTextField TotalField;
    private javax.swing.JTextField TotalField1;
    private javax.swing.JTextField iTemnameField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
